In [1]:
import numpy as np

In [5]:
#1. buatlah array integer dari 10 sampai 50
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [7]:
#2. buatlah array integer dari 10 sampai 50 dengan kelipatan 2
np.arange(10,50,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [9]:
#3. buatlah data array 3 baris 3 kolom 0 sampai 8
np.arange(0,9).reshape(3,3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
#4. buatlah data array dengan nilai 25 data secara random
np.random.rand(25)

array([0.21558685, 0.831532  , 0.8286764 , 0.83140819, 0.77259864,
       0.44136401, 0.58736208, 0.71412573, 0.84395301, 0.61685652,
       0.88411082, 0.59037619, 0.6375673 , 0.31182058, 0.01490974,
       0.98895631, 0.25040624, 0.72792102, 0.23730716, 0.67461532,
       0.5122384 , 0.03860637, 0.56639429, 0.41414497, 0.63633026])

In [22]:
#5. buatlah soal seperti gambar
arr = np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [23]:
#6.dari soal no.5 tampilkan data array seperti ini:
arr[2:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [31]:
#7. dari soal no 5 tampilkan nilai 20
arr[20]

20

In [27]:
#8. dari soal no 5 tampilkan data array seperti ini?


20

In [32]:
#9. dari soal no 5 tampilkan max, min, argmax dan argmin
arr.max()

25

In [33]:
arr.min()

0

In [34]:
arr.argmax()

25

In [35]:
arr.argmin()

0

In [47]:
#10. dari soal no 5 tampilkan index yang nilainya lebih dari 10 dan kurang sama dengan 20 sehingga seperti ini:
newarr = arr[arr>10]
newarr[newarr<=20]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])